# Generated by Django 3.1.7 on 2021-03-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0003_auto_20210313_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cakes', models.ManyToManyField(to='cakes.Cake')),
            ],
        ),
    ]
