# Generated by Django 3.1.7 on 2021-03-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='biscuit',
            name='desc',
            field=models.TextField(default='Опис'),
        ),
        migrations.AddField(
            model_name='cake',
            name='desc',
            field=models.TextField(default='Опис'),
        ),
        migrations.AddField(
            model_name='cream',
            name='desc',
            field=models.TextField(default='Опис'),
        ),
        migrations.AddField(
            model_name='decoration',
            name='desc',
            field=models.TextField(default='Опис'),
        ),
        migrations.AddField(
            model_name='filling',
            name='desc',
            field=models.TextField(default='Опис'),
        ),
    ]
