# Generated by Django 3.1.7 on 2021-04-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0005_auto_20210314_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biscuit',
            name='img',
            field=models.ImageField(blank=True, upload_to='biscuit/'),
        ),
    ]
