# Generated by Django 3.1.7 on 2021-04-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0006_auto_20210426_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='img',
            field=models.ImageField(blank=True, default=None, upload_to='cakes/'),
        ),
        migrations.AlterField(
            model_name='cream',
            name='img',
            field=models.ImageField(blank=True, upload_to='creams/'),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='img',
            field=models.ImageField(blank=True, upload_to='decors/'),
        ),
        migrations.AlterField(
            model_name='filling',
            name='img',
            field=models.ImageField(blank=True, upload_to='fillings/'),
        ),
    ]
