# Generated by Django 3.1.7 on 2021-04-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0007_auto_20210426_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiscuitDiameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.IntegerField(default=0.0)),
                ('coefficient', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='biscuit',
            name='diameter',
        ),
        migrations.AddField(
            model_name='biscuit',
            name='diameter',
            field=models.ManyToManyField(to='cakes.BiscuitDiameters'),
        ),
    ]
