# Generated by Django 3.1.7 on 2021-04-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0008_auto_20210426_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biscuit',
            name='diameter',
            field=models.ManyToManyField(blank=True, default=None, to='cakes.BiscuitDiameters'),
        ),
    ]
