# Generated by Django 3.1.7 on 2021-04-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0011_auto_20210426_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(default='no addr', max_length=400),
        ),
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='orders',
            name='name',
            field=models.CharField(default='noname', max_length=200),
        ),
        migrations.AddField(
            model_name='orders',
            name='surname',
            field=models.CharField(default='nosur', max_length=200),
        ),
        migrations.AddField(
            model_name='orders',
            name='telephone',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
    ]
