# Generated by Django 3.1.7 on 2021-06-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0013_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='cake',
            new_name='cakes',
        ),
    ]
