# Generated by Django 3.1.7 on 2021-06-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0014_auto_20210603_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biscuit', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cakes.biscuit')),
                ('cream', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cakes.cream')),
                ('decoration', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cakes.decoration')),
                ('diameter', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='cakes.cakediameters')),
                ('filling', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cakes.filling')),
            ],
        ),
    ]
